// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvugqxrgxzjlrvqptcme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dWdxeHJneHpqbHJ2cXB0Y21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODM2MzcsImV4cCI6MjA2NDE1OTYzN30.kdAnOuehNeqYYt92HUBhXUrxPQx8SWxGMNjDUSlT_9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);